name: Build All

on: [push]

jobs:
  build:
    name: Build for ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "Windows",
              os: windows-latest,
              environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            }
          - {
              name: "Linux",
              os: ubuntu-latest
            }
          - {
              name: "macOS",
              os: macos-latest
            }

    steps:
      - name: Linux Install yasm
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install yasm

      - name: macOS Install yasm
        if: matrix.config.os == 'macos-latest'
        run: |
          brew install yasm

      - name: VCPKG
        run: vcpkg install ffmpeg[avcodec]:x64
